<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/1/16
 * Time: 8:27
 */
namespace app\modules\AppBase\base\appbase\base;
use Yii;
class BaseDb2 extends BaseCommonDB
{
    function __construct()
    {
        parent::__construct(Yii::$app->db2); // TODO: Change the autogenerated stub
    }
}