<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2015/12/23
 * Time: 11:19
 */
namespace app\modules\AppBase\base\appbase;
class ManageBC extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}