<?php
/**
 * User: gjc
 *  2015/7/15 11:32
 */
namespace app\modules\AppBase\base\appbase;
use Exception;
use yii\web\Controller;
class SiteBC extends Controller
{
    private $pagestartime;
    private $pageendtime;
    public function beforeAction($action)
    {
        $this->pagestartime = microtime();
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
    public function afterAction($action, $result)
    {
        $ba = new BaseAnalyze();
        try {
            $content = '';
            $this->pageendtime = microtime();
            $starttime = explode(" ", $this->pagestartime);
            $endtime = explode(" ", $this->pageendtime);
            $totaltime = $endtime[0] - $starttime[0] + $endtime[1] - $starttime[1];
            $timecost = sprintf("%s", $totaltime);
            $content .= "\t" . $timecost;
            $content .= " \r\n";
            $ba->writeToAnal('++waste time: ' . $content);
            return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
        } catch (Exception $e) {
            $ba->writeToAnal('++error: ' . $e->getMessage());
            return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
        }
    }
}